#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &
#### AUTOSTART ####
exec dbus-run-session bspwm &
$HOME/.config/bspwm/autostart.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#rules
bspc rule -a Firefox desktop=^2 follow=true state=tiled
bspc rule -a Brave-browser desktop=^2 follow=true state=tiled
bspc rule -a Thunar desktop=^3 follow=true state=tiled
bspc rule -a Zathura desktop=^4 state=tiled follow=true
bspc rule -a mpv desktop=^9 state=tiled follow=true
bspc rule -a zoom desktop=^1 state=tiled follow=true
bspc rule -a Soffice follow=false desktop=^5
bspc rule -a Zotero follow=false desktop=^6

#### BSPWM configuration ####
bspc config border_radius 10
bspc config border_width 2
bspc config window_gap 8
bspc config split_ratio 0.55

bspc config single_monocle false
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config click_to_focus true
bspc config focus_by_distance true
bspc config focus_follows_pointer false
bspc config history_aware_focus true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config focused_border_color "#74c7ec"
bspc config normal_border_color "#575268"
bspc config presel_feedback_color "#74c7ec"


#### BSPWM configuration ####
bspc config border_radius 10
bspc config border_width 2
bspc config window_gap 8
bspc config split_ratio 0.55

bspc config single_monocle false
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config click_to_focus true
bspc config focus_by_distance true
bspc config focus_follows_pointer false
bspc config history_aware_focus true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config focused_border_color "#74c7ec"
bspc config normal_border_color "#575268"
bspc config presel_feedback_color "#74c7ec"
