#!/usr/bin/env zsh

file="$1"; shift
case "$(basename "$file" | tr '[:upper:]' '[:lower:]')" in
#*.tar*) tar tf "$file" ;;
#*.zip) unzip -l "$file" ;;
#*.rar) unrar l "$file" ;;
#*.7z) 7z l "$file" ;;
*.avi|*.mp4|*.mkv|*.webm)
	mpv "$file"
	;;
*.pdf|*.ps|*.djvu)
	zathura "$file"
	;;
*.epub)
	zathura "$file"
	;;
*.odt|*.ods|*.odp|*.odg|*.odf|*.odb|*.doc|*.docx)
	# FIXME: soffice crashes when launched via shell-async '&soffice'
	soffice "$file" >/dev/null 2>&1
	;;
*.jpg|*.jpeg|*.png|*.bmp|*.tiff)
	feh "$file"
	;;
*.svg)
	inkscape "$file"
	;;
*.gif)
	mpv -a "$file"
	;;
*)
	nvim "$file"
    ;;
esac
