#aliases
alias poweroff='loginctl poweroff'
alias reboot='loginctl reboot'
alias pull='git pull'
alias ga='git add'
alias gp='git push'
alias xi='sudo xbps-install'
alias xr='sudo xbps-remove -R'
alias xup='sudo xbps-install -Suv'
alias ls='ls -a --color'
alias v='nvim'
alias sv='sudo nvim'
alias mk='sudo make install'
alias gc='git clone'
alias sub='git submodule update --init'
alias dot='cd $HOME/dotfiles/'
