#!/bin/bash

DIR0="$HOME/.config/berry"

pgrep -x sxhkd >/dev/null || sxhkd -c "$HOME/.config/berry/sxhkdrc" &
$HOME/.config/berry/autostart.sh &

berryc name_desktop 0 "1"
berryc name_desktop 1 "2"
berryc name_desktop 2 "3"
berryc name_desktop 3 "4"
berryc name_desktop 4 "5"
berryc name_desktop 5 "6"
berryc name_desktop 6 "7"
berryc name_desktop 7 "8"
berryc name_desktop 8 "9"
berryc name_desktop 9 "10"

# Set decoration geometry
berryc border_width 3
berryc inner_border_width 0
berryc title_height 0
berryc edge_gap 45 10 10 10

# Set decoration colors
berryc focus_color 74c7ec
berryc unfocus_color 1e1e2e
berryc inner_focus_color 74c7ec
berryc inner_unfocus_color 1e1e2e
berryc text_focus_color 1e1e2e
berryc text_unfocus_color cdd6f4

# Other options
berryc smart_place "true"
berryc draw_text "true"
berryc edge_lock "true"
berryc decorate_new "false"
berryc set_font "Iosevka Nerd Font-12"
