#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
	herbstclient "$@"
}

hc emit_hook reload

#autorun
xsetroot -cursor_name left_ptr &
xrandr --output HDMI-1 --mode 1920x1080 --rate 60 &
xset s off &
xset -dpms &
pgrep -x picom >/dev/null || picom --config ~/.config/picom/picom.conf &
feh --bg-scale --no-fehbg /home/dimitris/dotfiles/Backgrounds/wallhaven-7pj8jo_2560x1440.png &
xclip &
setxkbmap -model pc104 -layout us,gr -option 'grp:alt_shift_toggle' &
pgrep -x dunst >/dev/null || dunst -c ~/.config/dunst/dunstrc &
pgrep -x sxhkd >/dev/null || sxhkd -c $HOME/.config/sxhkd/sxhkdrc &

# remove all existing keybindings
hc keyunbind --all

# tags (Font-Awesome)
TAG_NAMES=({"     ", "     ","     ","      ","     ","     ","     ","    ","     "})
#TAG_NAMES=({"  1   ", "  2   ","  3   ","   4   ","  5   ","  6   ","  7   ","  8  ","  9  ",})
TAG_KEYS=({1..9})

# keybindings
source $HOME/.config/herbstluftwm/keys

# theme
source $HOME/.config/herbstluftwm/theme

# rules
source $HOME/.config/herbstluftwm/rules

# find the panel
panel=~/.config/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1); do
	# start it on each monitor
	"$panel" "$monitor" &
done
